language: go

go:
  - 1.9.x

notifications:
  slack:
    on_success: change
    on_failure: change

env:
 - RELEASE=docker_update SLEEP=150

script:
 - go test -v ./...
 - bash install/setup.sh /tmp/appdir
 - bash install/import.sh lexdata /tmp/appdir $RELEASE || bash install/import.sh lexdata /tmp/appdir master
 - bash install/start_server.sh -a /tmp/appdir &
 - export pid=$!
 - echo "pronlex server running on pid $pid. wait for $SLEEP seconds before shutting down"
 - sleep $SLEEP
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pid
 - docker build . -t pronlex 
