language: go

go:
  - 1.9.x

notifications:
  email:
    on_success: change
    on_failure: change

env:
 - RELEASE=docker_update SLEEP=60

script:
 - set -e
 - go test -v ./... 
 - bash install/setup.sh /tmp/appdir
 
 - export GOPATH=`go env GOPATH`
 - export PATH=$PATH:$GOPATH/bin
 - CMDDIR="$GOPATH/src/github.com/stts-se/pronlex/lexserver"
 - switches="-ss_files /tmp/appdir/symbol_sets/ -db_files /tmp/appdir/db_files/ -static $CMDDIR/static"
 - cd $CMDDIR && go run *.go $switches -test
 #- bash install/start_server.sh -a /tmp/appdir &
 
 - bash install/import.sh lexdata /tmp/appdir $RELEASE || bash install/import.sh lexdata /tmp/appdir master
 - bash install/start_server.sh -a /tmp/appdir &
 - export pid=$!
 - echo "pronlex server running on pid $pid. wait for $SLEEP seconds before shutting down"
 - sleep $SLEEP
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pid
 
 - docker build . -t pronlex 
