language: go

go:
  - 1.9.x

before_script:
 - ls install

script:
 - go test -v ./... && bash sh install/standalone/install.sh /tmp/appdir && lexserver -ss_files /tmp/appdir/symbol_sets/ -db_files /tmp/appdir/db_files/ -static /tmp/appdir/.static/ -test 

