language: go

os: linux
dist: bionic

go:
  - 1.13.x

notifications:
  email:
    on_success: change
    on_failure: change

env:
 - RELEASE=master SLEEP=60
 - RELEASE=master SLEEP=60 DO_IMPORT=1

#addons:
#  mariadb: '10.1'

#services: mysql

script:
 - set -e
 - sudo apt-get install mariadb-client mariadb-server
 - cat go.mod
 #- sudo mysql -u root < scripts/mariadb_setup.sql
 - go get github.com/securego/gosec/cmd/gosec
 - gosec ./...
 - go get honnef.co/go/tools/cmd/staticcheck
 - staticcheck ./...

 - bash scripts/setup.sh -a /tmp/appdir/sqlite -e sqlite

 - | 
   if [ -v DO_IMPORT ]; then
     bash scripts/import.sh lexdata /tmp/appdir/sqlite $RELEASE
   fi

 - bash scripts/start_server.sh -a /tmp/appdir/sqlite -e sqlite -p 8766 &
 - export pida=$!
 - echo "pronlex sqlite server started on pid $pida. wait for $SLEEP seconds before shutting down"
 
 - bash scripts/setup.sh -a /tmp/appdir/mariadb -e mariadb -l 'speechoid:@tcp(127.0.0.1:3306)'

 - | 
   if [ -v DO_IMPORT ]; then
     bash scripts/import.sh lexdata /tmp/appdir/mariadb $RELEASE
   fi

 - bash scripts/start_server.sh -a /tmp/appdir/mariadb -e mariadb -l 'speechoid:@tcp(127.0.0.1:3306)' -p 8767
 - export pidb=$!
 - echo "pronlex mariadb server started on pid $pidb. wait for $SLEEP seconds before shutting down"
 - sleep $SLEEP

 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pida
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pidb
 
 - go test -v ./... 
