language: go

go:
  - 1.13.x

notifications:
  email:
    on_success: change
    on_failure: change

env:
 - RELEASE=master SLEEP=60
 - RELEASE=master SLEEP=60 DO_IMPORT=1

#addons:
#  mariadb: '10.1'

#services: mysql

script:
 - set -e
 #- sudo apt-get install mariadb-client mariadb-server
 - sudo apt-get install software-properties-common dirmngr
 - sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
 - sudo add-apt-repository 'deb [arch=amd64] http://ftp.nluug.nl/db/mariadb/repo/10.4/debian buster main'
 - sudo apt update
 - sudo apt install mariadb-client mariadb-server
 - cat go.mod
 - sudo mysql -u root < scripts/mariadb_setup.sql
 - go test -v ./... 
 - go get github.com/securego/gosec/cmd/gosec
 - gosec ./...
 - go get honnef.co/go/tools/cmd/staticcheck
 - staticcheck ./...
 - bash scripts/setup.sh /tmp/appdir

 - | 
   if [ -v DO_IMPORT ]; then
     bash scripts/import.sh lexdata /tmp/appdir master
   fi

 - bash scripts/start_server.sh -a /tmp/appdir -e sqlite &
 - export pid=$!
 - echo "pronlex server started on pid $pid. wait for $SLEEP seconds before shutting down"
 - sleep $SLEEP
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pid
 
