language: go

go:
  - 1.9.x

notifications:
  slack:
    on_success: change
    on_failure: change

script:
 - go test -v ./... && bash install/setup.sh /tmp/appdir && bash install/start_server.sh -a /tmp/appdir &
 - export pid=$!
 - echo "pronlex server running on pid $pid"
 - sleep 300
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pid


