language: go

go:
  - 1.9.x

notifications:
  email:
    on_success: change
    on_failure: change

env:
 - RELEASE=docker_update SLEEP=60
 - RELEASE=docker_update SLEEP=60 DO_IMPORT=1

script:
 - set -e
 - go test -v ./... 
 - bash install/setup.sh /tmp/appdir

 - | 
   if [ -v DO_IMPORT ]; then
     bash install/import.sh lexdata /tmp/appdir $RELEASE || bash install/import.sh lexdata /tmp/appdir master
   fi
   
 - bash install/start_server.sh -a /tmp/appdir &
 - export pid=$!
 - echo "pronlex server running on pid $pid. wait for $SLEEP seconds before shutting down"
 - sleep $SLEEP
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pid
 
 - docker build . -t pronlex 
