language: go

os: linux
dist: bionic

go:
  - 1.13.x

notifications:
  email:
    on_success: change
    on_failure: change

env:
 - RELEASE=master SLEEP=60 DO_IMPORT=1 ENGINE=sqlite PORT=8787 APPDIR=/tmp/appdir LOC="'speechoid:@tcp(127.0.0.1:3306)'"
 - RELEASE=master SLEEP=60 DO_IMPORT=1 ENGINE=mariadb PORT=8787 APPDIR=/tmp/appdir LOC=/tmp/appdir

#addons:
#  mariadb: '10.1'

#services: mysql

script:
 - set -e
 - sudo apt-get install mariadb-client mariadb-server
 - cat go.mod
 #- sudo mysql -u root < scripts/mariadb_setup.sql
 - go get github.com/securego/gosec/cmd/gosec
 - gosec ./...
 - go get honnef.co/go/tools/cmd/staticcheck
 - staticcheck ./...

 - bash scripts/setup.sh -a $APPDIR -e $ENGINE -l $LOC

 - go test -v ./... 

 - |
     if [ -v DO_IMPORT ]; then
         bash scripts/import.sh -e $ENGINE -f lexdata -a $APPDIR -r $RELEASE -l $LOC
     fi

 - bash scripts/start_server.sh -a $APPDIR -e $ENGINE -l $LOC -p $PORT
 - export pid=$!

 - echo "pronlex $ENGINE server started on pid $pid. wait for $SLEEP seconds before shutting down"
 - sleep $SLEEP

 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pid
 
