# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Status

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Go report card
      uses: creekorful/goreportcard-action@v1.0

    - name: Installation
      run: |
       sudo apt install mariadb-client mariadb-server siege
       cat go.mod

    - name: Test
      run: go test -v ./...

    - name: Setup
      run: |
       #RELEASE=master SLEEP=60 DO_IMPORT=1 ENGINE=sqlite PORT=8780 APPDIR=/tmp/appdir/sqlite LOC=/tmp/appdir/sqlite
       #RELEASE=master SLEEP=60 DO_IMPORT=1 ENGINE=mariadb PORT=8780 APPDIR=/tmp/appdir/mariadb LOC='speechoid:@tcp(127.0.0.1:3306)'
       bash scripts/setup.sh -a /tmp/appdir/mariadb -e mariadb -l 'speechoid:@tcp(127.0.0.1:3306)'
       bash scripts/setup.sh -a /tmp/appdir/sqlite -e sqlite -l /tmp/appdir/sqlite
       bash scripts/import.sh -e sqlite -f wikispeech-lexdata -a /tmp/appdir/sqlite -r master -l /tmp/appdir/sqlite
       bash scripts/import.sh -e mariadb -f wikispeech-lexdata -a /tmp/appdir/sqlite -r master -l 'speechoid:@tcp(127.0.0.1:3306)'

    - name: Start server
      run: |
       bash scripts/start_server.sh -a $APPDIR -e $ENGINE -l $LOC -p $PORT &
       sleep 20

       curl -f http://localhost:8780/ping
